# These are supported funding model platforms

github: Mraprguild 
patreon: mraprguild 
open_collective: mraprguild 
ko_fi: mraprguild 
tidelift: # mraprguild 
community_bridge: mraprguild 
liberapay: mraprguild 
issuehunt: mraprguild 
otechie: Mraprguild
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
